# CONFIGURATION

# point to the initial location of the stars
# we can use it to load pre-generated stars, e.g., a star map
# based on the Milky Way
# input: random_stars.dat
input: visible_stars.csv
sep: ','

# alternatively, specify a number of stars to generate
# dynamically (randomly over the sky)
star_number: 250

# gravitational wave parameters
amplitude: 0.1
time_samples: 1000
